### ISSUE TITLE
error upgrading encfs to 1.9 (missing: FUSE_INCLUDE_DIR FUSE_LIBRARIES)

### ISSUE THREAD

**Issue by maspotts** [Homebrew/homebrew-fuse#66] opened 2016-09-12 16:34 UTC
On OSX 10.11.6

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
Last 15 lines from /Users/mike/Library/Logs/Homebrew/encfs/01.cmake:
-- Check for working CXX compiler: /opt/brew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /opt/brew/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find FUSE (missing: FUSE_INCLUDE_DIR FUSE_LIBRARIES)
Call Stack (most recent call first):
  /opt/brew/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFUSE.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:55 (find_package)

**Comment by maspotts** [comment] 2016-09-19 16:28
Is the right forum for reporting (install) bugs?

**Comment by maspotts** [comment] 2016-09-20 05:14
I have had brew cask osxfuse installed all along. Just manually upgraded it (to 3.5.0) but got same error from encfs install.  OS is 10.11.6.  Any help gratefully appreciated!

**Comment by maspotts** [comment] 2016-09-21 19:38
Update: I just tried to upgrade to encfs 1.9 on a second machine (also running 10.11.6) and got the same error.  Is there some brew-specific thing I need to do to fix this perhaps?

**Comment by jonathanou** [comment] 2016-09-25 07:43
I ran into the same error on macOS Sierra (10.12) and was able to resolve the issue by installing OSX Fuse (https://osxfuse.github.io/).  I installed the stable version 3.5.0.

@maspotts I restarted my terminal app after upgrading OSX Fuse, was that why you couldn't get it to work?

**Comment by maspotts** [comment] 2016-09-26 05:25
@jonathanou thanks for that!  I started a new terminal but got the same error.  Did you install osxfuse via the brew cask osxfuse?  (I used the cask, followed by a manual update via the preferences pane.)

**Comment by jonathanou** [comment] 2016-09-26 05:29
@maspotts I didn't use cask, I installed the OSX fuse package directly using the installer.  Perhaps you should give it a try, it may be something with cask that's causing the problem.

**Comment by maspotts** [comment] 2016-09-26 05:38
@jonathanou just tried that, but no luck.  did you also install the optional "macfuse compatibility"?

**Comment by jonathanou** [comment] 2016-09-26 05:41
Yes, I believe so.  After the install I also restarted my terminal since
the error message looked like it was missing either environment variables
or some script variable.  I restarted the terminal to make sure everything
was initialized correctly.

**Comment by maspotts** [comment] 2016-09-26 05:51
rats: tried all that, no luck :(  thanks for the help anyway!

**Comment by maspotts** [comment] 2016-10-20 04:38
I figured this out: to work around my problem I had to patch the encfs.rb formula to add:

    ENV.append "CMAKE_INCLUDE_PATH", "/usr/local/include", ":"
    ENV.append "CMAKE_LIBRARY_PATH", "/usr/local/lib", ":"

I assume this is necessary because I have my homebrew installed into /opt rather than /usr/local, although I'm not enough of a homebrew/ruby expert to confirm this.  Nevertheless with this patch the install works.  I think this is a no-op if homebrew is installed into /usr/local.  Would it be reasonable for me to submit a pull request for encfs.rb on this basis?

**Comment by umireon** [comment] 2016-11-21 15:18
@maspotts The problem is all the Homebrew's libraries are installed under /opt but only the OSXFUSE is installed under /usr/local regardless of Homebrew's prefix.

I would personally like to pass options `-DFUSE_INCLUDE_DIR=/usr/local/include -DFUSE_LIBRARIES=/usr/local/lib` to `cmake`, avoiding accidental inclusions of libraries.

**Comment by umireon** [comment] 2016-11-23 11:48
This will be fixed by Homebrew/brew#1549.

**Comment by maspotts** [comment] 2016-11-23 21:11
@umireon Many, many thanks: very elegant and timely!!

**Comment by maspotts** [comment] 2016-12-16 05:26
Just curious: I see the osxfuse_requirements.rb file was updated (with the references to /usr/local), but I still can't build the encfs formula: do I need to do anything to force those requirements to be picked up?

**Comment by umireon** [comment] 2016-12-16 16:03
@maspotts I think that problem should be fixed in upstream.

**Comment by maspotts** [comment] 2016-12-18 03:21
Thanks!  Any idea when it will show up in a "brew update"?  I see I have the new requirements file already, but I don't understand how/when the encfs.rb formula will become dependent on it...

**Comment by MikeMcQuaid** [comment] 2017-01-27 09:22
https://github.com/Homebrew/brew/pull/1549 was merged and part of `brew update`.

**Closed by MikeMcQuaid** 2017-01-27 09:22 UTC
